In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("D:\practice_data_set\home_prices_in_monroe.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      5 non-null      int64  
 1   bedrooms  4 non-null      float64
 2   age       5 non-null      int64  
 3   price     5 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 292.0 bytes


In [4]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [6]:
np.mean(df['bedrooms'])

3.75

In [9]:
a = round(np.mean(df['bedrooms']))
a

4

In [12]:
df1 = df.fillna(4)

In [13]:
df1.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [14]:
model = LinearRegression()

In [15]:
model.fit(df1[['area','bedrooms','age']],df1['price'])

LinearRegression()

In [22]:
coef = model.coef_
coef

array([   165.47645491, -72491.11505997, -10725.23322968])

In [23]:
intercept = model.intercept_
intercept

543902.7099067072

In [18]:
model.predict(df1[['area','bedrooms','age']])

array([542163.48289649, 589489.11594847, 590408.70724123, 600387.60550866,
       757551.08840515])

In [21]:
model.predict([[3000,3,40]])

E:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([393849.40026655])

In [27]:
y_pred = 3000*coef[0]+3*coef[1]+40*coef[2]+intercept
y_pred

393849.40026654815

In [29]:
model.predict([[2500,4,5]])

E:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([614003.22079076])